import Link from 'next/link'
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Mail, Phone } from 'lucide-react'
import { school, leadership, history, objectives } from '@/data/school'

const pageCopy: Record<string, { eyebrow: string; title: string; intro: string }> = {
  about: { eyebrow: 'Our story', title: 'Rooted in faith. Growing with purpose.', intro: 'St. Kalooli Lwanga SS Mulajje is a Catholic-founded secondary school serving Mulajje Parish and the wider Luweero community since 1986.' },
  academics: { eyebrow: 'Learning at our core', title: 'Education that prepares students for life.', intro: 'We are committed to academic excellence, student development, a positive study environment, co-curricular growth and disciplined character formation.' },
  admissions: { eyebrow: 'Begin your journey', title: 'A place to learn, belong and become.', intro: 'Prospective students and parents are warmly invited to contact the school for current admissions information and guidance.' },
  leadership: { eyebrow: 'Our people', title: 'Steady leadership, shared responsibility.', intro: 'Meet the team serving the school community with professionalism, commitment and care.' },
  gallery: { eyebrow: 'School life', title: 'A glimpse of our community.', intro: 'Official school photographs will be added here as they become available. This gallery is ready for campus, student life, academics and events.' },
  contact: { eyebrow: 'Get in touch', title: 'We would be glad to hear from you.', intro: 'Reach the school team for admissions, school information and general enquiries.' },
  news: { eyebrow: 'Updates', title: 'News and announcements.', intro: 'This space is ready for school news, academic updates, events and community announcements.' },
}

export default async function InnerPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const copy = pageCopy[slug] ?? pageCopy.about
  return <main className="min-h-screen bg-[#f7f4ee] text-[#142f4a]"><header className="bg-[#142f4a] px-5 py-5 text-white"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/" className="font-serif text-xl">St. Kalooli Lwanga SS Mulajje</Link><Link href="/" className="text-sm text-white/70 hover:text-white">Home</Link></div></header><section className="bg-[#142f4a] px-5 pb-24 pt-16 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[0.28em] text-[#e7bd5f]">{copy.eyebrow}</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-tight md:text-7xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">{copy.intro}</p></div></section><section className="mx-auto max-w-6xl px-5 py-16"><div className="grid gap-5 md:grid-cols-2">{slug === 'leadership' ? leadership.map((person) => <article className="rounded-2xl border border-[#142f4a]/10 bg-white p-6" key={person.name}><div className="flex size-16 items-center justify-center rounded-full bg-[#dce3e7] font-serif text-xl">{person.initials}</div><h2 className="mt-5 font-serif text-2xl">{person.name}</h2><p className="mt-1 text-sm text-[#bd703f]">{person.role}</p></article>) : slug === 'about' ? history.map((item) => <article className="rounded-2xl border border-[#142f4a]/10 bg-white p-6" key={item.title}><p className="font-serif text-3xl text-[#bd703f]">{item.year}</p><h2 className="mt-3 font-serif text-2xl">{item.title}</h2><p className="mt-3 leading-7 text-slate-600">{item.text}</p></article>) : slug === 'contact' ? <><article className="rounded-2xl bg-white p-8"><Mail className="text-[#bd703f]" /><h2 className="mt-5 font-serif text-2xl">Email the school</h2><a className="mt-3 block text-slate-600 underline" href={`mailto:${school.email}`}>{school.email}</a></article><article className="rounded-2xl bg-white p-8"><Phone className="text-[#bd703f]" /><h2 className="mt-5 font-serif text-2xl">Call or WhatsApp</h2><p className="mt-3 text-slate-600">{school.phone} · {school.alternativePhone}</p></article></> : (slug === 'academics' ? ['Academic excellence', 'Teaching and learning', 'Student development', 'Discipline and character'].map((item) => <article className="rounded-2xl bg-white p-7" key={item}><CheckCircle2 className="text-[#bd703f]" /><h2 className="mt-5 font-serif text-2xl">{item}</h2><p className="mt-3 leading-7 text-slate-600">Editable section for official school information and updates.</p></article>) : objectives.slice(0, 4).map((item) => <article className="rounded-2xl bg-white p-7" key={item}><BookOpen className="text-[#bd703f]" /><p className="mt-4 leading-7 text-slate-600">{item}</p></article>))}</div><Link href="/" className="mt-12 inline-flex items-center gap-2 font-semibold text-[#a65c4b]"><ArrowLeft size={16} /> Back to home</Link></section></main>
}
